name: Makefile CI

on:
  push:https://github.com/MKYGRAPHICS7/device_xiaomi_sky_Breeze
    branches: [ "device_xiaomi_sky_Breeze" ] 
  pull_request:https://github.com/MKYGRAPHICS7/device_xiaomi_sky_Breeze
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
